package_name: 'rampant-pack'
version: '4.0.5'

packages:
  server:
    builder: "vanilla"
    directories:
      - common
      - server
    host: "nerv.local"
    dir: "/Volumes/Ryoji/Minecraft/rampant-pack"

  vanilla:
    builder: "vanilla"
    directories: &CLIENT_DIRS
      - common
      - client

  technic:
    builder: "technic"
    forge_version: "1.7.10-10.13.2.1230"
    directories: *CLIENT_DIRS
