package_name: 'rampant-pack'
version: '4.0.4-SNAPSHOT'

packages:
  server:
    builder: "vanilla"
    directories:
      - common
      - server
    host: "nerv.local"
    dir: "/Volumes/Ryoji/Minecraft/rampant-pack"

  vanilla:
    builder: "vanilla"
    directories: &CLIENT_DIRS
      - common
      - client

  technic:
    builder: "technic"
    directories:
      <<: *CLIENT_DIRS
